# -*- coding: utf-8 -*-
"""
Created on Tue Mar 22 10:14:25 2022

@author: AnshumaanChauhan
"""
'''
Edits by Anthony Liardo
'''


#NAS PARAMETERS
CONTROLLER_SAMPLING_EPOCHS = 11
SAMPLES_PER_CONTROLLER_EPOCH = 37
CONTROLLER_TRAINING_EPOCHS = 5
ARCHITECTURE_TRAINING_EPOCHS = 7
CONTROLLER_LOSS_ALPHA = 0.9 

#CONTROLLER(LSTM) PARAMETERS
CONTROLLER_LSTM_DIM = 100
CONTROLLER_OPTIMIZER = 'Adam'
CONTROLLER_LEARNING_RATE = 0.05
CONTROLLER_DECAY = 0.1
CONTROLLER_MOMENTUM = 0.0
CONTROLLER_USE_PREDICTOR = False

#CNN ARCH PARAMETERS
MAX_ARCHITECTURE_LENGTH = 5
MLP_DECAY = 0.0
MLP_MOMENTUM = 0.0
MLP_LOSS_FUNCTION = 'mean_absolute_error'
MLP_ONE_SHOT = False

#As using time-series dataset for checking of CNN training and testing 
TARGET_CLASSES = 1
FORECAST_MINUTES = 5
#PATIENT_NUMBER = 540
TOP_N = 5
